# coding: utf-8

"""
    Token Tracker Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from tokentracker.models.tokentracker_adjust_token_balance_response import TokentrackerAdjustTokenBalanceResponse

class TestTokentrackerAdjustTokenBalanceResponse(unittest.TestCase):
    """TokentrackerAdjustTokenBalanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokentrackerAdjustTokenBalanceResponse:
        """Test TokentrackerAdjustTokenBalanceResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokentrackerAdjustTokenBalanceResponse`
        """
        model = TokentrackerAdjustTokenBalanceResponse()
        if include_optional:
            return TokentrackerAdjustTokenBalanceResponse(
                new_balance = ''
            )
        else:
            return TokentrackerAdjustTokenBalanceResponse(
        )
        """

    def testTokentrackerAdjustTokenBalanceResponse(self):
        """Test TokentrackerAdjustTokenBalanceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
